# BANCOS DE DADOS SÃO CONJUNTOS DE TABELAS
# TABELAS SÃO CONJUNTOS DE REGISTROS

# O COMANDO ABAIXO CRIA UM BANCO DE DADOS
CREATE DATABASE cadastro;

# O COMANDO ABAIXO SERVE PARA UTILIZAR O BANCO QUE FOI CRIADO
USE cadastro;

# CRIANDO UMA TABELA
CREATE TABLE pessoas (
    nome VARCHAR(30),
    idade TINYINT,
    sexo FLOAT,
    peso FLOAT,
    altura FLOAT,
    nacionalidade VARCHAR(20)
);

# O COMANDO ABAIXO SERVER PARA DESCREVER A TABELA 'PESSOAS'
# SERVE PARA VERIFICAR COMO A TABELA FICOU.
DESCRIBE pessoas;

# O COMANDO ABAIXO SERVE PARA MOSTRAR TODOS OS BANCOS DE DADOS
SHOW DATABASES;
