# O COMANDO ABAIXO SERVER PARA DELETAR O BANCO DE DADOS QUE FOI CRIADO
DROP DATABASE cadastro;

# CRIANDO E CONFIGURANDO O BANCO DE DADOS COM OS CARACTERES QUE UTILIZAMOS NO BRASIL.
CREATE DATABASE cadastro
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

# USANDO O BANCO DE DADOS CRIADOS
USE cadastro;

# CRIANDO UMA TABELA COM MAIS 'CONSTRAINTS -> RESTRIÇÕES'
CREATE TABLE pessoa(
`id` INT NOT NULL AUTO_INCREMENT,
`nome` VARCHAR(30) NOT NULL, # 'NOT NULL' SERVE PARA OBRIGAR QUE ESTE CAMPO SEJA PREENCHIDO!
`nascimento` DATE NOT NULL,
`sexo` ENUM('M','F') NOT NULL, # 'ENUM('M','F')' SERVE PARA OBRIGAR QUE O CAMPO SEJA PREENCHIDO SOMENTE COM OS DADOS DEFINIDOS!
`peso` DECIMAL(5,2) NOT NULL, # 'DECIMAL(5,2)' SERVE PARA DEFINIR COMO SERÁ GUARDADO A INFORMAÇÃO COM VIRGULA!
`altura` DECIMAL(3,2) NOT NULL,
`nacionalidade` VARCHAR(20) DEFAULT 'Brasil', # SE O CAMPO NÃO FOR PREENCHIDO, POR PADRÃO SERÁ CONFORME O QUE FOI ESTABELECIDO 'DEFAULT Brasil'
PRIMARY KEY(id)
)DEFAULT CHARSET = utf8;

# OBS: COLOCAR CRASES `` NO NOME DA TABELA E CRASE NOS NOMES DAS COLUNAS PERMITE PREENCHER OS DADOS COM ESPAÇOS E ACENTOS!!!
# TUPLAS: SÃO DOIS REGISTROS IGUAIS

DESCRIBE pessoa;