USE cadastro;

SHOW TABLES;

DESCRIBE pessoa;

SELECT * FROM pessoa;

# O COMANDO ABAIXO SERVE PARA ADICIONAR UMA NOVA COLUNA NA TABELA 'pessoa'
ALTER TABLE pessoa
ADD COLUMN profissao VARCHAR(20);

# O COMANDO ABAIXO SERVE PARA DELETAR A COLUNA QUE FOI CRIADA NA TABELA 'pessoa'
ALTER TABLE pessoa
DROP COLUMN profissao;

# O COMANDO ABAIXO SERVE PARA CRIAR UMA NOVA COLUNA, ESCOLHENDO UM DETERMINADO LUGAR NA TABELA 'pessoa'
ALTER TABLE pessoa
ADD COLUMN profissao VARCHAR (20) AFTER nome;

# O COMANDO ABAIXO SERVE PARA ALTERAR O TIPO QUE FOI DEFINIDO ANTERIORMENTE 'VARCHAR(20)' => 'VARCHAR(40)'
ALTER TABLE pessoa
MODIFY COLUMN profissao VARCHAR (40);
# VERIFIQUE QUE O TAMANHO DO TIPO 'VARCHAR' FOI ALTERADO
DESCRIBE pessoa;

# O COMANDO ABAIXO SERVE PARA ALTERAR O NOME DA COLUNA QUE FOI DEFINIDO
ALTER TABLE pessoa
CHANGE COLUMN profissao prof VARCHAR(20);
# VERIFIQUE QUE FOI ALTERADO O NOME DA COLUNA
DESCRIBE pessoa;

# COMANDO ABAIXO SERVE PARA ALTERAR O NOME DA TABELA
ALTER TABLE Werike
RENAME TO aula06_01;
# VEJA QUE O NOME ANTIGO DA TABELA 'pessoa' PASSOU A SER 'Werike'
DESCRIBE aula06_01;