# O COMANDO ABAIXO SERVE PARA CRIAR UMA TABELA SE ELA NÃO EXISTIR
CREATE TABLE IF NOT EXISTS curso(
nome VARCHAR(30) NOT NULL UNIQUE, # 'UNIQUE' SIGNIFICA UNICO. OU SEJA, O NOME SERÁ UNICO!
descricao TEXT,
carga INT UNSIGNED, # GUARDANDO REGISTROS SEM SINAL
totalaulas INT UNSIGNED,
ano YEAR DEFAULT '2020'
)DEFAULT CHARSET = utf8;

DESCRIBE curso;

# COLOCANDO A CHAVE PRIMARIA
ALTER TABLE curso
ADD COLUMN idcurso INT FIRST;

# DEFININDO QUEM É A CHAVE PRIMARIA
ALTER TABLE curso
ADD PRIMARY KEY (idcurso);

# O COMANDO ABAIXO SERVE PARA APAGAR O BANCO DE DADOS
# => DROP DATABASE cadastro;
# O COMANDO ABAIXO SERVE PARA APAGAR A TABELA
# => DROP TABLE curso;