USE cadastro;

# COMANDOS ABAIXO SÃO FUNÇÕES DE AGREGAÇÃO!!!

# O COMANDO ABAIXO SERVE PARA O TOTAL DE CURSOS CADASTRADOS
SELECT * FROM cursos; # VEJA QUE EXISTE VARIOS CURSOS REGISTRADOS
SELECT COUNT(*) FROM cursos; # 'COUNT(*)' BUSCA FAZ A CONTAGEM DE TUDO.

# REALIZANDO A CONTAGEM COM A FUNAÇÃO DE AGREGAÇÃO 'COUNT(*)'
SELECT * FROM cursos
WHERE carga > 40;

SELECT COUNT(*) FROM cursos
WHERE carga > 40;

# QUAL O CURSO QUE POSSUI A MAIOR CARGA?
SELECT * FROM cursos
ORDER BY carga;

SELECT MAX(carga) FROM cursos
ORDER BY carga;

# DENTRO DOS CURSOS DO ANO DE 2016, QUAIS EU TIVE MAIS AULAS?
SELECT MAX(totaulas) AS Aulas FROM cursos # 'AS' SERVE PARA APILIDAR A COLUNA DO RESULT SET() 
WHERE ano = '2016';

# DENTRO DOS CURSOS DO ANO DE 2016, QUAIS EU TIVE MENOS AULAS?
SELECT nome, MIN(totaulas) FROM cursos
WHERE ano = '2016';

# O COMANDO ABAIXO SERVE PARA SOMAR
SELECT SUM(totaulas) FROM cursos
WHERE ano = '2016';

# O COMANDO ABAIXO SERVE PARA MOSTRAR A MÉDIA
SELECT AVG(totaulas) FROM cursos
WHERE ano = '2016';