USE cadastro;

# O COMANDO ABAIXO SERVE PARA LOCALIZAR TODAS AS LINHAS ONDE O NOME COMECE COM A LETRA 'p'
SELECT nome FROM cursos
WHERE nome LIKE 'p%'; # O COMANDO (LIKE - NESTE CASO É SEMELHANTE) O PORCENTO INDICA QUAL PALAVRA INICIA COM A LETRA 'p'.

# MESMO COMANDO QUE O DE CIMA, PORÉM É ALTERADO A POSIÇÃO DO '%' PARA MOSTRAR RESULTADOS DIFERENTES.
SELECT nome FROM cursos
WHERE nome LIKE '%a'; # O PORCENTO INDICA AS PALAVRAS/DADOS QUE DEVEM FINALIZAR COM A LETRA 'a'.

# MESMO COMANDO QUE O DE CIMA, BUSCANDO A LETRA EM QUALQUER POSIÇÃO.
SELECT nome FROM cursos
WHERE nome LIKE '%a%'; # VAI RETORNAR A LETRA QUE ESTA EM QUALQUER LUGAR NA PALAVRA

# MESMO COMANDO QUE O DE CIMA, PORÉM NÃO QUERO UMA DETERMINADA LETRA EM NENHUMA POSIÇÃO NA PALAVRA
SELECT nome FROM cursos
WHERE nome NOT LIKE '%a%'; # O 'NOT' SERVE PARA RETORNAR PALAVRAS SEM NENHUMA LETRA 'a'

# RETORNANDO UM DADO ONDE TERMINA COM ALGUMA COISA 
SELECT nome FROM cursos
WHERE nome LIKE 'PH%P_'; # TERMINA COM 'P' E MAIS ALGUMA COISA '_'

# O COMANDO ABAIXO SERVE PARA ELEMINAR DADOS REPETIDOS
SELECT * FROM gafanhotos;
SELECT nacionalidade FROM gafanhotos; # VEJA COMO PAISES SE REPETEM VARIAS VEZES!
SELECT DISTINCT nacionalidade FROM gafanhotos; # 'DISTINCT' SERVE PARA INFORMAR DADOS QUENÃO SEJAM REPETIDOS.
SELECT DISTINCT nacionalidade FROM gafanhotos ORDER BY nacionalidade; # PARA FINALIZAR, COLOQUEI EM LISTA ORDENADA.

# FAZENDO O MESMO COMANDO ACIMA, PORÉM EM OUTRA TABELA.
SELECT * FROM cursos;
SELECT carga FROM cursos;
SELECT DISTINCT carga FROM cursos; # QUAIS SÃO AS CARGAS HORARIAS DOS MEUS CURSOS?