USE CADASTRO;

SHOW TABLES;

SELECT * FROM cursos;

SELECT DISTINCT carga FROM cursos
ORDER BY carga;

SELECT * FROM cursos;
SELECT DISTINCT totaulas FROM cursos # O COMANDO 'DISTINCT' SERVE PARA RETORNAR SOMENTE UM REGISTRO DA TABELA. EXCLUÍNDO TODOS OS REGISTROS REPETIDOS.
ORDER BY totaulas;

SELECT totaulas FROM cursos
GROUP BY totaulas # SERVE PARA AGRUPAR TODOS OS DADOS REPETIDO E RETORNA UMA VEZ O VALOR('COMO SE ESTIVESSE EXCLUÍDO OS DADOS REPETIDOS, PORÉM, ELES ESTÃO AGRUPADOS')
ORDER BY totaulas;

SELECT totaulas, COUNT(*) FROM cursos  
GROUP BY totaulas # COMO OS DADOS RETORNADOS ESTÃO AGRUPADOS, EU QUERO QUE FAÇA UMA SOMA DE QUANTOS DADOS AGRUPADOS/JUNTOS ESTÃO UTILIZANDO O 'COUNT (*)'
ORDER BY totaulas; # SERVE PARA ORDENAR DO MAIOR PARA O MENOR.
# VEJA QUE NA PRIMEIRA LINHA EU TENHO UM TOTAL DE 2 CURSOS COM TOTAL DE 8 AULAS...

# OCOMANDO ABAIXO SERVE PARA TIRAR A 'PROVA REAL' DOS RESULTADOS RETORNADOS PELOS COMANDOS ACIMA 'GROUP BY'
SELECT * FROM cursos
WHERE totaulas = 8;
# A PRIMEIRA LINHA DO COMANDO ACIMA, RETORNOU QUE EXISTE 2 CURSOS COM TOTAL DE 8 AULAS.
# EXECUTANDO ESSE COMANDO PODEMOS VER QUE REALENTE EXISTE 2 CURSOS COM TOTAL DE 8 AULAS.

# OUTRO EXEMPLO SERVE PARA CONTAR QUANTOS CURSOS(nome) QUANTAS CARGAS DE HORAS DE AULAS(carga) TÊM UM VALOR IGUAL DE 30 AULAS(totaulas)
SELECT * FROM cursos;
SELECT carga, COUNT(*) AS Total FROM cursos WHERE totaulas = 30
GROUP BY carga
ORDER BY carga;
# O RESULTADO FOI DE 2 CURSOS DE CARGA DE HORAS AULAS E 4 CURSOS DE CARGA DE 60 HORAS AULAS.alter

# ESSE COMANDO SERVE PARA TIRAR A PROVA REAL DO RESULTADO DO COMANDO ASSIMA
SELECT * FROM cursos WHERE totaulas = 30;

# ESTUDANDO O COMANDO 'HAVING' QUE É A CONDIÇÃO PARA O 'GROUP BY'
SELECT ano, COUNT(*) AS Total FROM cursos
GROUP BY ano
HAVING ano > 2016 # OBS: O COMANDO 'HAVING(QUEM TEM)' SÓ FUNCIONA SE FOR O MESMO CAMPO/COLUNA DECLARADA NO COMANDO 'GROUP BY'
ORDER BY COUNT(*) DESC;

# JUNTANDO OS SELECT
SELECT AVG(carga) FROM cursos; # 'AVG(COLUNA)' SERVE PARA RETORNAR A MÉDIA QUE FOI (36.3333) => VOU USAR ESSE RESULTADO NO COMANDO ABAIXO!!!

# ESSE COMANDO RETORNA 
SELECT * FROM cursos
WHERE ano > 2015
GROUP BY carga
HAVING carga > 36.3 # OU SEJA, A CARGA QUE FOR MAIOR QUE A MÉDIA TOTAIS DE CARGA, QUE FOI O REULTADO REGISTRADO ACIMA (36.3333).
ORDER BY carga;

# ESSE COMANDO VAI FAZER O MESMO QUE O COMANDO ACIMA, PORÉM, SEMPRE QUE TIVER !!!UMA ALTERAÇÃO NA MÉDIA DE CARGA!!! ELE RETORNA O DADO COM A ALTERAÇÃO.
SELECT carga, COUNT(*) AS Total FROM cursos
WHERE ano > 2015
GROUP BY carga
HAVING carga > (SELECT AVG(carga) FROM cursos); # AGRUPE A CARGA QUEM TEM A CARGA MAIOR QUE A MÉDIA DE CARGA!!!