# REGRAS DE CARDINALIDADES DO MODELO RELACIONAL

# CARDINALIDADE (1:1) - UM PARA UM 
# A ENTIDADE DOMINANTE FICA DO LADO ESQUERDO, E ELA RECEBE A CHAVE ESTRANGEIRA DO LADO DIREITO.

# CARDINALIDADE (1:N) - UM PARA MUITOS
# SEMPRE PEGAR A CHAVE PRIMARIA DA CARDINALIDADE '1(UM)' E JOGAR DENTRO DA CARDINALIDADE 'N(MUITOS)'

# CARDINALIDADE (N:N) - MUITOS PARA MUITOS
# O RELACIONAMENTO SEMPRE VAI VIRAR UMA ENTIDADE, E É GERADO DOIS NOVOS RELACIONAMENTOS.
# E A REGRA É (1:N) => LIGANDO A ENTIDADE AO RELACIONAMENTO/ENTIDADE
# E A REGRA É (N:1) => LIGANDO A OUTRA ENTIDADE AO RELACIONAMENTO/ENTIDA
# SEMPRE MANDAR A CHAVE DA ENTIDADE '1(UM)' PARA O RELACIONAMENTO/ENTIDADE 'N(MUITOS)'