# ADICIONANDO UMA CHAVE ESTRANGEIRA (FOREING KEY) - RELACIONAMENTO DE 1:1

USE cadastro;

SHOW TABLES;

DESCRIBE gafanhotos;
DESCRIBE cursos;

ALTER TABLE gafanhotos
ADD COLUMN cursopreferido INT; # O TIPO DESTA COLUNA CRIADA, TEM QUE SER A MESMA QUE A CHAVE PRIMARIA DE OUTRA TABELA. VEJA ABAIXO O TIPO DA TABELA CURSOS.

DESCRIBE cursos; # A CHAVE PRIMARIA É 'idcurso' E SEU TIPO É 'int'. NA COLUNA CRIADA ACIMA, VAI SERVIR PARA RECEBER ESSA CHAVE PRIMARIA, COMO CHAVE ESTRANGEIRA, E DEVE TER O MESMO TIPO.

# ADICIONANDO A COLUNA CRIADA ACIMA 'cursopreferido' COMO CHAVE ESTRANGEIRA.
ALTER TABLE gafanhotos
ADD FOREIGN KEY (cursopreferido) # AQUI ESTOU ADICIONANDO A COLUNA 'cursopreferido' COMO UMA CHAVE ESTRANGEIRA.
REFERENCES cursos(idcurso); # PRECISO REFERENCIAR QUEM É A CHAVE PRIMARIA DA OUTRA TABELA.

# CONFIRMANDO SE A COLUNA 'cursopreferido' É UMA CHAVE ESTRANGEIRA. VERIFIQUE A COLUNA 'Key' SE NA LINHA 'Cursopreferido' O CAMPO PREENCHIDO ESTA COMO 'MUL' QUE SIGNIFICA MULTIPLA.
SELECT * FROM gafanhotos; 
SELECT * FROM cursos;

# ATUALIZE A COLUNA 'cursopreferido' DA COLUNA 'id' LINHA '1' COMO CURSO PREFERIDO MySQL='6'.
UPDATE gafanhotos
SET cursopreferido = '6'
WHERE id = '1'
LIMIT 1;

# ERRO: INTEGRIDADE REFERENCIAL
DELETE FROM cursos WHERE idcurso = '6';
# ESSE ERRO ACONTECE QUANDO TENTO APAGAR UMA TABELA RELACIONADA COM OUTRA, E NÃO VAI DA PARA APAGAR. SE O DADO NÃO TIVER RELAÇÃO É POSSÍVEL APAGAR. VEJA O EXEMPLO ABAIXO. 

# APAGADO UM CURSO PREFERIDO QUE NÃO TEM RELAÇÃO. OU SEJA, É UM CURSO ONDE NINGUÉM ESTA CURSANDO, OU NINGUÉM TEM UMA RELAÇÃO COM ESSE CURSO.
SELECT * FROM gafanhotos; # VEJA QUE NINGÉM ESTA CURSANDO O CURSO DE NÚMERO '7' QUE É CURSO DE 'WORD'.

SELECT * FROM cursos; # SENDO ASSIM, COMO NINGÉM TEM RELAÇÃO COM O CURSO DE '7-WORD' EU POSSO DELETAR O CURSO PREFERIDO DE ALGUÉM/id.
DELETE FROM cursos WHERE idcurso = '7';  # VEJA QUE O CURSO DE NÚMERO '7-WORD' FOI APAGADO COM SUCESSO! O CURSO DE NÚMERO '6' PULA PARA O CURSO DE NÚMERO '8'.