# São ENGINE (InnoDB - XtraDB) => Suportam transações 'ACID'

# TRANSASÕES ACID

# A => ATOMICAS: NÃO PODE SER DIVIDAS EM SUB-TAREFAS(OU TODA TAREFA É FEITA OU NÃO É CONSIDERADO)

# C => CONSISTÊNCIA: SE O BANCO DE DADOS ESTAVA CONSISTENTE ANTES DE UMA TRANSAÇÃO, ELE DEVE CONTINUAR CONSISTENTE APÓS A TRANSAÇÃO. SE ALGO DE ERRADO ACONTECE, TUDO É DESFEITO E VOLTA PARA O ESTADO ANTERIOR.

# I => ISOLAMENTO: SE VÁRIOS USUÁRIOS ESTÃO REALIZANDO CONSULTAS, NENHUM RESULTADO DESSAS CONSULTAS PODEM INTERFERIR UM AO OUTRO.

# D => DURABILIDADE: OS DADOS TÊM QUE SER DURÁVEIS O QUANTO TEMPO FOR NECESSÁRIO.